# Generated by Django 4.0.4 on 2022-05-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='photos_product/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
